import tkinter as tk

# Read the grid and pathfinding results from the text files generated by the C++ program
grid_path = "../out/grid.txt"
with open(grid_path, "r") as f:
    grid_width, grid_height = [int(x) for x in f.readline().split()]
    rows = [row.rstrip("\n") for row in f]

pathfinding_path = "../out/pathfinding.txt"
with open(pathfinding_path, "r") as f:
    pgrid_width, pgrid_height, start_x, start_y, goal_x, goal_y = [int(x) for x in f.readline().split()]
    closed = [int(x) for x in f.readline().split()]
    path = [int(x) for x in f.readline().split()]

    # Sanity checks to ensure that the data read from the files is consistent and valid
    assert(pgrid_height == grid_height and pgrid_width == grid_width)
    assert len(closed) == grid_width * grid_height
    assert len(path) == grid_width * grid_height



# Create a Tkinter window to visualize the grid and the results of the A* pathfinding algorithm
root = tk.Tk()

# Set the size of the window and center it on the screen
width = 750
height = 750

screen_width = root.winfo_screenwidth()
screen_height = root.winfo_screenheight()

x = (screen_width - width) // 2
y = (screen_height - height) // 2

root.geometry(f"{width}x{height}+{x}+{y}")

# Set the title and background color of the window
root.title("Grid and A* visualization")
root.configure(bg="white")

# If the grid is too large, the script won't be able to visualize it properly
if (max(grid_height, grid_width) > 100):
    raise Exception("Grid is too large to be visualized using this script\nGrid's size should not be bigger than 100x100")
else:
    # Calculate the size of each cell in the grid based on the window size and the grid dimensions, and create a canvas to draw on
    cell_size = (width - 50) / max(grid_height, grid_width)
    canvas = tk.Canvas(
        root,
        width = grid_width * cell_size,
        height = grid_height * cell_size,
        bg = "white",
        highlightthickness=0,
        bd=0
    )

    # Pack the canvas into the window and set it to expand to fill the available space
    canvas.pack(expand = "true")

    # Iterate through the grid and draw each cell on the canvas with a color corresponding to its state (wall, open, closed, or part of the path)
    for y, row in enumerate(rows):
        for x, cell in enumerate(row):
            index = y * grid_width + x
            if cell == "#":
                color = "black"
            else:
                color = "white"
                if closed[index] == 1: color = "cyan2"
                if path[index] == 1: color = "orange"

            x1 = x * cell_size
            y1 = y * cell_size
            x2 = x1 + cell_size
            y2 = y1 + cell_size

            canvas.create_rectangle(
                x1, y1, x2, y2,
                fill = color,
                outline = "whitesmoke"
            )

    # Draw the start and goal positions on the canvas with distinct colors (green for start and red for goal)
    canvas.create_rectangle(
        start_x * cell_size, start_y * cell_size, start_x * cell_size + cell_size, start_y * cell_size + cell_size,
        fill="green3",
        outline="green3"
    )

    canvas.create_rectangle(
        goal_x * cell_size, goal_y * cell_size, goal_x * cell_size + cell_size, goal_y * cell_size + cell_size,
        fill="red",
        outline="red"
    )

    root.mainloop()